### ISSUE TITLE
Can I have instructions for Mac OS please?

### ISSUE THREAD

**Issue by GemKosan** [Abbas-b-b/VLCPlaylistRememberer#1]

**Comment by Abbas-b-b** [comment]
@GemKosan Please test these directories:

- For all users:
```/Applications/VLC.app/Contents/MacOS/share/lua/extensions/``` and ```/Applications/VLC.app/Contents/MacOS/share/lua/playlist/```

- For a specific user:
```/Users/%user_name%/Library/Application Support/org.videolan.vlc/lua/extensions/``` and ```/Users/%user_name%/Library/Application Support/org.videolan.vlc/lua/playlist/```

**Comment by ha3an-118** [comment]
@Abbas-b-b  it's work  greate
